### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by syzygy1** [tthsqe12/cas#2]
A warning that you might want to fix:

$ g++ -O3 -o cas cas.cpp
cas.cpp: In function ‘int main()’:
cas.cpp:73:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing 32 bytes into a region of size 24 overflows the destination [-Wstringop-overflow=]
     memcpy(EXPR_FLT1, one, FLT_LIMBS + 8*2);
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by syzygy1** [comment]
Fixed now.

**Comment by tthsqe12** [comment]
@syzygy1 ,
I would like to get a gui version working on linux using gtk. Unfortunately, I have been unable to get the gtk dev tools installed on my box. Do you know how much work it would be to get gtk version working that is analogous to the windows version?

**Comment by syzygy1** [comment]
As far as I'm aware, a gtk UI that works on Windows should also work on Linux as far as the gtk part is concerned. (But it seems you haven't committed any gtk code yet?)

Btw:
$ g++ -O3 -o cas cas.cpp
cas.cpp:159:10: fatal error: large.cpp: No such file or directory
 #include "large.cpp"
          ^~~~~~~~~~~
compilation terminated.

**Comment by syzygy1** [comment]
(And it would be more convenient if you could leave the cas binary out of the repository. Otherwise git complains each time I merge in new changes, since my compilation differs from what is in the repository.)

**Comment by tthsqe12** [comment]
The command line version can now be compiled. So you are saying that one should be able to take windows-agnostic gtk code that works on windows and have it work on linux. I guess I will be trying to get a working gtk on windows...

**Comment by tthsqe12** [comment]
@syzygy1,
Do you have any idea what this means? Does it mean that my ubuntu installation is permanently broken? I tried installing the gnome-devel package from the software center. This did not help.
```
$ sudo apt-get install libgtk2.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libgtk2.0-dev : Depends: libgtk2.0-0 (= 2.24.23-0ubuntu1) but 2.24.23-0ubuntu1.4 is to be installed
                 Depends: gir1.2-gtk-2.0 (= 2.24.23-0ubuntu1) but 2.24.23-0ubuntu1.4 is to be installed
                 Depends: libglib2.0-dev (>= 2.27.3) but it is not going to be installed
                 Depends: libgdk-pixbuf2.0-dev (>= 2.21.0) but it is not going to be installed
                 Depends: libpango1.0-dev (>= 1.20) but it is not going to be installed
                 Depends: libatk1.0-dev (>= 1.29.2) but it is not going to be installed
                 Depends: libcairo2-dev (>= 1.6.4-6.1) but it is not going to be installed
                 Depends: libxext-dev (>= 1:1.0.1-2) but it is not going to be installed
                 Depends: libxinerama-dev (>= 1:1.0.1-4.1) but it is not going to be installed
                 Depends: libxi-dev (>= 1:1.0.1-4) but it is not going to be installed
                 Depends: libxrandr-dev (>= 2:1.2.99) but it is not going to be installed
                 Depends: libxcursor-dev but it is not going to be installed
                 Depends: libxfixes-dev (>= 1:3.0.0-3) but it is not going to be installed
                 Depends: libxcomposite-dev (>= 1:0.2.0-3) but it is not going to be installed
                 Depends: libxdamage-dev (>= 1:1.0.1-3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by syzygy1** [comment]
I don't use Ubuntu or APT myself, but maybe this helps:
https://askubuntu.com/questions/140246/how-do-i-resolve-unmet-dependencies-after-adding-a-ppa

**Comment by tthsqe12** [comment]
Of course I had tried everything on that page.
But I have good news!
I tried `sudo aptitude install libgtk2.0-dev`. The first option it proposed didn't work, but the second one did!
So now the command `gcc base.c -o base `pkg-config --cflags --libs gtk+-2.0` from https://developer.gnome.org/gtk-tutorial/stable/c39.html#SEC-HELLOWORLD works.
